name: exemplifica
description: Aprenda matemática de um jeito simples.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 9.0.3+15

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  # package_info_plus: ^5.0.1
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.24.9

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/expoentes/
    - images/mult_div/
    - images/parentesis/
    - images/regras_sinal/
    - images/soma_sub/
    - images/operacoes/equacao_1/
    - images/operacoes/equacao_2/
    - images/operacoes/fatorial/
    - images/operacoes/funcoes/
    - images/operacoes/juros_compostos/
    - images/operacoes/juros_simples/
    - images/operacoes/mdc/
    - images/operacoes/mmc/
    - images/operacoes/porcentagem/
    - images/operacoes/raiz_quadrada/
    - images/operacoes/regra_de3/
    - images/operacoes/tabuada/
    - images/calculadoras/
    - images/calculadoras_1.png
    - images/simbolos.png
    - images/logotipo_exemplifica.png

  fonts:
    - family: Person
      fonts:
        - asset: icons/Person.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
