name: exemplifica
description: Aprenda matemática de um jeito simples.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.1+6

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.24.9

flutter-assets:
  auto-generate: false
  assets-path: assets
  output-path: lib/assets
  ignore-ext: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/expoentes/
    - assets/images/mult_div/
    - assets/images/parentesis/
    - assets/images/regras_sinal/
    - assets/images/soma_sub/
    - assets/images/operacoes/
    - assets/images/operacoes/equacao_1/
    - assets/images/operacoes/equacao_2/
    - assets/images/operacoes/fatorial/
    - assets/images/operacoes/juros_compostos/
    - assets/images/operacoes/juros_simples/
    - assets/images/operacoes/mdc/
    - assets/images/operacoes/mmc/
    - assets/images/operacoes/porcentagem/
    - assets/images/operacoes/regra_de3/
    - assets/images/operacoes/tabuada/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: Person
      fonts:
        - asset: assets/icons/Person.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
