name: Build APK

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.8'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Get app version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk \
          build/app/outputs/flutter-apk/exemplifica_v${VERSION}.apk

      - name: Upload Artifact (Actions)
        uses: actions/upload-artifact@v4
        with:
          name: exemplifica_v${{ env.VERSION }}
          path: build/app/outputs/flutter-apk/exemplifica_v${{ env.VERSION }}.apk
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/exemplifica_v${{ env.VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}