// Generated by Flutter Assets

// ignore_for_file: unused_field, camel_case_types, non_constant_identifier_names, library_private_types_in_public_api

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
        
class Assets extends StatelessWidget {
  final AssetsData assets;
  final Widget child;

  const Assets({
    super.key,
    required this.assets,
    required this.child,
  });

  static AssetsData of(BuildContext context) {
    final widget = context.dependOnInheritedWidgetOfExactType<_InheritedAssets>();
    return widget?.assets ?? AssetsData.light();
  }

  @override
  Widget build(BuildContext context) {
    return _InheritedAssets(
      assets: assets,
      child: child,
    );
  }
}

class _InheritedAssets extends InheritedWidget {
  final AssetsData assets;

  const _InheritedAssets({
    required this.assets,
    required super.child,
  });

  @override
  bool updateShouldNotify(covariant _InheritedAssets oldWidget) => assets != oldWidget.assets;
}

class AssetsData {
  static AssetsData? _light;
  static AssetsData? _dark;

  factory AssetsData.light() => _light ??= AssetsData._(brightness: Brightness.light);
  factory AssetsData.dark() => _dark ??= AssetsData._(brightness: Brightness.dark);
  factory AssetsData.brightness(Brightness brightness) => brightness == Brightness.light ? AssetsData.light() : AssetsData.dark();

  final Brightness _brightness;

  AssetsData._({
    required Brightness brightness,
  })  : _brightness = brightness,
        icons = _assets_icons_dart._(brightness: brightness),
        images = _assets_images_dart._(brightness: brightness),
        svg = _assets_svg_dart._(brightness: brightness);

  final _assets_icons_dart icons;
  final _assets_images_dart images;
  final _assets_svg_dart svg;
}

class _assets_icons_dart {
  final Brightness _brightness;

  _assets_icons_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final Person_ttf = 'assets/icons/Person.ttf';
}

class _assets_images_dart {
  final Brightness _brightness;

  _assets_images_dart._({
    required Brightness brightness,
  })  : _brightness = brightness,
        expoentes = _assets_images_expoentes_dart._(brightness: brightness),
        mult_div = _assets_images_mult_div_dart._(brightness: brightness),
        operacoes = _assets_images_operacoes_dart._(brightness: brightness),
        parentesis = _assets_images_parentesis_dart._(brightness: brightness),
        regras_sinal = _assets_images_regras_sinal_dart._(brightness: brightness),
        soma_sub = _assets_images_soma_sub_dart._(brightness: brightness);

  final _assets_images_expoentes_dart expoentes;
  final _assets_images_mult_div_dart mult_div;
  final _assets_images_operacoes_dart operacoes;
  final _assets_images_parentesis_dart parentesis;
  final _assets_images_regras_sinal_dart regras_sinal;
  final _assets_images_soma_sub_dart soma_sub;

  final backapp_png = 'assets/images/backapp.png';
  final backgroundSplash_png = 'assets/images/backgroundSplash.png';
  final logotipo_exemplifica_png = 'assets/images/logotipo_exemplifica.png';
  final simbolos_png = 'assets/images/simbolos.png';
}

class _assets_images_expoentes_dart {
  final Brightness _brightness;

  _assets_images_expoentes_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final expoentes_2_png = 'assets/images/expoentes/expoentes_2.png';
  final expoentes_3_png = 'assets/images/expoentes/expoentes_3.png';
  final expoentes_4_png = 'assets/images/expoentes/expoentes_4.png';
  final expoentes_5_png = 'assets/images/expoentes/expoentes_5.png';
}

class _assets_images_mult_div_dart {
  final Brightness _brightness;

  _assets_images_mult_div_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final multiplica_divi_10_png = 'assets/images/mult_div/multiplica_divi_10.png';
  final multiplica_divi_11_png = 'assets/images/mult_div/multiplica_divi_11.png';
  final multiplica_divi_12_png = 'assets/images/mult_div/multiplica_divi_12.png';
  final multiplica_divi_2_png = 'assets/images/mult_div/multiplica_divi_2.png';
  final multiplica_divi_3_png = 'assets/images/mult_div/multiplica_divi_3.png';
  final multiplica_divi_4_png = 'assets/images/mult_div/multiplica_divi_4.png';
  final multiplica_divi_5_png = 'assets/images/mult_div/multiplica_divi_5.png';
  final multiplica_divi_6_png = 'assets/images/mult_div/multiplica_divi_6.png';
  final multiplica_divi_7_png = 'assets/images/mult_div/multiplica_divi_7.png';
  final multiplica_divi_8_png = 'assets/images/mult_div/multiplica_divi_8.png';
  final multiplica_divi_9_png = 'assets/images/mult_div/multiplica_divi_9.png';
}

class _assets_images_operacoes_dart {
  final Brightness _brightness;

  _assets_images_operacoes_dart._({
    required Brightness brightness,
  })  : _brightness = brightness,
        equacao_1 = _assets_images_operacoes_equacao_1_dart._(brightness: brightness),
        equacao_2 = _assets_images_operacoes_equacao_2_dart._(brightness: brightness),
        fatorial = _assets_images_operacoes_fatorial_dart._(brightness: brightness),
        funcoes = _assets_images_operacoes_funcoes_dart._(brightness: brightness),
        juros_compostos = _assets_images_operacoes_juros_compostos_dart._(brightness: brightness),
        juros_simples = _assets_images_operacoes_juros_simples_dart._(brightness: brightness),
        mdc = _assets_images_operacoes_mdc_dart._(brightness: brightness),
        mmc = _assets_images_operacoes_mmc_dart._(brightness: brightness),
        porcentagem = _assets_images_operacoes_porcentagem_dart._(brightness: brightness),
        raiz_quadrada = _assets_images_operacoes_raiz_quadrada_dart._(brightness: brightness),
        regra_de3 = _assets_images_operacoes_regra_de3_dart._(brightness: brightness),
        tabuada = _assets_images_operacoes_tabuada_dart._(brightness: brightness);

  final _assets_images_operacoes_equacao_1_dart equacao_1;
  final _assets_images_operacoes_equacao_2_dart equacao_2;
  final _assets_images_operacoes_fatorial_dart fatorial;
  final _assets_images_operacoes_funcoes_dart funcoes;
  final _assets_images_operacoes_juros_compostos_dart juros_compostos;
  final _assets_images_operacoes_juros_simples_dart juros_simples;
  final _assets_images_operacoes_mdc_dart mdc;
  final _assets_images_operacoes_mmc_dart mmc;
  final _assets_images_operacoes_porcentagem_dart porcentagem;
  final _assets_images_operacoes_raiz_quadrada_dart raiz_quadrada;
  final _assets_images_operacoes_regra_de3_dart regra_de3;
  final _assets_images_operacoes_tabuada_dart tabuada;
}

class _assets_images_operacoes_equacao_1_dart {
  final Brightness _brightness;

  _assets_images_operacoes_equacao_1_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final equacao1_2_png = 'assets/images/operacoes/equacao_1/equacao1_2.png';
  final equacao1_3_png = 'assets/images/operacoes/equacao_1/equacao1_3.png';
  final equacao1_4_png = 'assets/images/operacoes/equacao_1/equacao1_4.png';
  final equacao1_5_png = 'assets/images/operacoes/equacao_1/equacao1_5.png';
  final equacao1_6_png = 'assets/images/operacoes/equacao_1/equacao1_6.png';
  final equacao1_7_png = 'assets/images/operacoes/equacao_1/equacao1_7.png';
}

class _assets_images_operacoes_equacao_2_dart {
  final Brightness _brightness;

  _assets_images_operacoes_equacao_2_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final equacao2_10_png = 'assets/images/operacoes/equacao_2/equacao2_10.png';
  final equacao2_11_png = 'assets/images/operacoes/equacao_2/equacao2_11.png';
  final equacao2_12_png = 'assets/images/operacoes/equacao_2/equacao2_12.png';
  final equacao2_13_png = 'assets/images/operacoes/equacao_2/equacao2_13.png';
  final equacao2_14_png = 'assets/images/operacoes/equacao_2/equacao2_14.png';
  final equacao2_15_png = 'assets/images/operacoes/equacao_2/equacao2_15.png';
  final equacao2_16_png = 'assets/images/operacoes/equacao_2/equacao2_16.png';
  final equacao2_17_png = 'assets/images/operacoes/equacao_2/equacao2_17.png';
  final equacao2_2_png = 'assets/images/operacoes/equacao_2/equacao2_2.png';
  final equacao2_3_png = 'assets/images/operacoes/equacao_2/equacao2_3.png';
  final equacao2_4_png = 'assets/images/operacoes/equacao_2/equacao2_4.png';
  final equacao2_5_png = 'assets/images/operacoes/equacao_2/equacao2_5.png';
  final equacao2_6_png = 'assets/images/operacoes/equacao_2/equacao2_6.png';
  final equacao2_7_png = 'assets/images/operacoes/equacao_2/equacao2_7.png';
  final equacao2_8_png = 'assets/images/operacoes/equacao_2/equacao2_8.png';
  final equacao2_9_png = 'assets/images/operacoes/equacao_2/equacao2_9.png';
}

class _assets_images_operacoes_fatorial_dart {
  final Brightness _brightness;

  _assets_images_operacoes_fatorial_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final fatorial_10_png = 'assets/images/operacoes/fatorial/fatorial_10.png';
  final fatorial_11_png = 'assets/images/operacoes/fatorial/fatorial_11.png';
  final fatorial_12_png = 'assets/images/operacoes/fatorial/fatorial_12.png';
  final fatorial_13_png = 'assets/images/operacoes/fatorial/fatorial_13.png';
  final fatorial_14_png = 'assets/images/operacoes/fatorial/fatorial_14.png';
  final fatorial_15_png = 'assets/images/operacoes/fatorial/fatorial_15.png';
  final fatorial_16_png = 'assets/images/operacoes/fatorial/fatorial_16.png';
  final fatorial_17_png = 'assets/images/operacoes/fatorial/fatorial_17.png';
  final fatorial_18_png = 'assets/images/operacoes/fatorial/fatorial_18.png';
  final fatorial_19_png = 'assets/images/operacoes/fatorial/fatorial_19.png';
  final fatorial_2_png = 'assets/images/operacoes/fatorial/fatorial_2.png';
  final fatorial_20_png = 'assets/images/operacoes/fatorial/fatorial_20.png';
  final fatorial_21_png = 'assets/images/operacoes/fatorial/fatorial_21.png';
  final fatorial_3_png = 'assets/images/operacoes/fatorial/fatorial_3.png';
  final fatorial_4_png = 'assets/images/operacoes/fatorial/fatorial_4.png';
  final fatorial_5_png = 'assets/images/operacoes/fatorial/fatorial_5.png';
  final fatorial_6_png = 'assets/images/operacoes/fatorial/fatorial_6.png';
  final fatorial_7_png = 'assets/images/operacoes/fatorial/fatorial_7.png';
  final fatorial_8_png = 'assets/images/operacoes/fatorial/fatorial_8.png';
  final fatorial_9_png = 'assets/images/operacoes/fatorial/fatorial_9.png';
}

class _assets_images_operacoes_funcoes_dart {
  final Brightness _brightness;

  _assets_images_operacoes_funcoes_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final funcoes_10_png = 'assets/images/operacoes/funcoes/funcoes_10.png';
  final funcoes_11_png = 'assets/images/operacoes/funcoes/funcoes_11.png';
  final funcoes_12_png = 'assets/images/operacoes/funcoes/funcoes_12.png';
  final funcoes_13_png = 'assets/images/operacoes/funcoes/funcoes_13.png';
  final funcoes_14_png = 'assets/images/operacoes/funcoes/funcoes_14.png';
  final funcoes_15_png = 'assets/images/operacoes/funcoes/funcoes_15.png';
  final funcoes_16_png = 'assets/images/operacoes/funcoes/funcoes_16.png';
  final funcoes_17_png = 'assets/images/operacoes/funcoes/funcoes_17.png';
  final funcoes_18_png = 'assets/images/operacoes/funcoes/funcoes_18.png';
  final funcoes_19_png = 'assets/images/operacoes/funcoes/funcoes_19.png';
  final funcoes_2_png = 'assets/images/operacoes/funcoes/funcoes_2.png';
  final funcoes_20_png = 'assets/images/operacoes/funcoes/funcoes_20.png';
  final funcoes_21_png = 'assets/images/operacoes/funcoes/funcoes_21.png';
  final funcoes_22_png = 'assets/images/operacoes/funcoes/funcoes_22.png';
  final funcoes_23_png = 'assets/images/operacoes/funcoes/funcoes_23.png';
  final funcoes_24_png = 'assets/images/operacoes/funcoes/funcoes_24.png';
  final funcoes_25_png = 'assets/images/operacoes/funcoes/funcoes_25.png';
  final funcoes_26_png = 'assets/images/operacoes/funcoes/funcoes_26.png';
  final funcoes_27_png = 'assets/images/operacoes/funcoes/funcoes_27.png';
  final funcoes_28_png = 'assets/images/operacoes/funcoes/funcoes_28.png';
  final funcoes_29_png = 'assets/images/operacoes/funcoes/funcoes_29.png';
  final funcoes_3_png = 'assets/images/operacoes/funcoes/funcoes_3.png';
  final funcoes_30_png = 'assets/images/operacoes/funcoes/funcoes_30.png';
  final funcoes_31_png = 'assets/images/operacoes/funcoes/funcoes_31.png';
  final funcoes_32_png = 'assets/images/operacoes/funcoes/funcoes_32.png';
  final funcoes_33_png = 'assets/images/operacoes/funcoes/funcoes_33.png';
  final funcoes_34_png = 'assets/images/operacoes/funcoes/funcoes_34.png';
  final funcoes_4_png = 'assets/images/operacoes/funcoes/funcoes_4.png';
  final funcoes_4_1_png = 'assets/images/operacoes/funcoes/funcoes_4_1.png';
  final funcoes_5_png = 'assets/images/operacoes/funcoes/funcoes_5.png';
  final funcoes_6_png = 'assets/images/operacoes/funcoes/funcoes_6.png';
  final funcoes_7_png = 'assets/images/operacoes/funcoes/funcoes_7.png';
  final funcoes_8_png = 'assets/images/operacoes/funcoes/funcoes_8.png';
  final funcoes_9_png = 'assets/images/operacoes/funcoes/funcoes_9.png';
}

class _assets_images_operacoes_juros_compostos_dart {
  final Brightness _brightness;

  _assets_images_operacoes_juros_compostos_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final jurosCompostos_2_png = 'assets/images/operacoes/juros_compostos/jurosCompostos_2.png';
  final jurosCompostos_3_png = 'assets/images/operacoes/juros_compostos/jurosCompostos_3.png';
  final jurosCompostos_4_png = 'assets/images/operacoes/juros_compostos/jurosCompostos_4.png';
  final jurosCompostos_5_png = 'assets/images/operacoes/juros_compostos/jurosCompostos_5.png';
  final jurosCompostos_6_png = 'assets/images/operacoes/juros_compostos/jurosCompostos_6.png';
  final jurosCompostos_7_png = 'assets/images/operacoes/juros_compostos/jurosCompostos_7.png';
  final jurosCompostos_8_png = 'assets/images/operacoes/juros_compostos/jurosCompostos_8.png';
  final jurosCompostos_9_png = 'assets/images/operacoes/juros_compostos/jurosCompostos_9.png';
}

class _assets_images_operacoes_juros_simples_dart {
  final Brightness _brightness;

  _assets_images_operacoes_juros_simples_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final jurosSimples_2_png = 'assets/images/operacoes/juros_simples/jurosSimples_2.png';
  final jurosSimples_3_png = 'assets/images/operacoes/juros_simples/jurosSimples_3.png';
  final jurosSimples_4_png = 'assets/images/operacoes/juros_simples/jurosSimples_4.png';
  final jurosSimples_5_png = 'assets/images/operacoes/juros_simples/jurosSimples_5.png';
  final jurosSimples_6_png = 'assets/images/operacoes/juros_simples/jurosSimples_6.png';
}

class _assets_images_operacoes_mdc_dart {
  final Brightness _brightness;

  _assets_images_operacoes_mdc_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final mdc_2_png = 'assets/images/operacoes/mdc/mdc_2.png';
  final mdc_3_png = 'assets/images/operacoes/mdc/mdc_3.png';
}

class _assets_images_operacoes_mmc_dart {
  final Brightness _brightness;

  _assets_images_operacoes_mmc_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final mmc_2_png = 'assets/images/operacoes/mmc/mmc_2.png';
  final mmc_3_png = 'assets/images/operacoes/mmc/mmc_3.png';
  final mmc_4_png = 'assets/images/operacoes/mmc/mmc_4.png';
  final mmc_5_png = 'assets/images/operacoes/mmc/mmc_5.png';
}

class _assets_images_operacoes_porcentagem_dart {
  final Brightness _brightness;

  _assets_images_operacoes_porcentagem_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final porcentagem_10_png = 'assets/images/operacoes/porcentagem/porcentagem_10.png';
  final porcentagem_2_png = 'assets/images/operacoes/porcentagem/porcentagem_2.png';
  final porcentagem_3_png = 'assets/images/operacoes/porcentagem/porcentagem_3.png';
  final porcentagem_4_png = 'assets/images/operacoes/porcentagem/porcentagem_4.png';
  final porcentagem_5_png = 'assets/images/operacoes/porcentagem/porcentagem_5.png';
  final porcentagem_6_png = 'assets/images/operacoes/porcentagem/porcentagem_6.png';
  final porcentagem_7_png = 'assets/images/operacoes/porcentagem/porcentagem_7.png';
  final porcentagem_8_png = 'assets/images/operacoes/porcentagem/porcentagem_8.png';
  final porcentagem_9_png = 'assets/images/operacoes/porcentagem/porcentagem_9.png';
}

class _assets_images_operacoes_raiz_quadrada_dart {
  final Brightness _brightness;

  _assets_images_operacoes_raiz_quadrada_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final raizQuadrada_10_png = 'assets/images/operacoes/raiz_quadrada/raizQuadrada_10.png';
  final raizQuadrada_11_png = 'assets/images/operacoes/raiz_quadrada/raizQuadrada_11.png';
  final raizQuadrada_2_png = 'assets/images/operacoes/raiz_quadrada/raizQuadrada_2.png';
  final raizQuadrada_3_png = 'assets/images/operacoes/raiz_quadrada/raizQuadrada_3.png';
  final raizQuadrada_4_png = 'assets/images/operacoes/raiz_quadrada/raizQuadrada_4.png';
  final raizQuadrada_5_png = 'assets/images/operacoes/raiz_quadrada/raizQuadrada_5.png';
  final raizQuadrada_6_png = 'assets/images/operacoes/raiz_quadrada/raizQuadrada_6.png';
  final raizQuadrada_7_png = 'assets/images/operacoes/raiz_quadrada/raizQuadrada_7.png';
  final raizQuadrada_8_png = 'assets/images/operacoes/raiz_quadrada/raizQuadrada_8.png';
  final raizQuadrada_9_png = 'assets/images/operacoes/raiz_quadrada/raizQuadrada_9.png';
}

class _assets_images_operacoes_regra_de3_dart {
  final Brightness _brightness;

  _assets_images_operacoes_regra_de3_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final regra_de3_10_png = 'assets/images/operacoes/regra_de3/regra_de3_10.png';
  final regra_de3_11_png = 'assets/images/operacoes/regra_de3/regra_de3_11.png';
  final regra_de3_12_png = 'assets/images/operacoes/regra_de3/regra_de3_12.png';
  final regra_de3_13_png = 'assets/images/operacoes/regra_de3/regra_de3_13.png';
  final regra_de3_2_png = 'assets/images/operacoes/regra_de3/regra_de3_2.png';
  final regra_de3_3_png = 'assets/images/operacoes/regra_de3/regra_de3_3.png';
  final regra_de3_4_png = 'assets/images/operacoes/regra_de3/regra_de3_4.png';
  final regra_de3_5_png = 'assets/images/operacoes/regra_de3/regra_de3_5.png';
  final regra_de3_6_png = 'assets/images/operacoes/regra_de3/regra_de3_6.png';
  final regra_de3_7_png = 'assets/images/operacoes/regra_de3/regra_de3_7.png';
  final regra_de3_8_png = 'assets/images/operacoes/regra_de3/regra_de3_8.png';
  final regra_de3_9_png = 'assets/images/operacoes/regra_de3/regra_de3_9.png';
}

class _assets_images_operacoes_tabuada_dart {
  final Brightness _brightness;

  _assets_images_operacoes_tabuada_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final tabuada_2_png = 'assets/images/operacoes/tabuada/tabuada_2.png';
  final tabuada_3_png = 'assets/images/operacoes/tabuada/tabuada_3.png';
  final tabuada_4_png = 'assets/images/operacoes/tabuada/tabuada_4.png';
}

class _assets_images_parentesis_dart {
  final Brightness _brightness;

  _assets_images_parentesis_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final parentesis_png = 'assets/images/parentesis/parentesis_.png';
  final parentesis_1_png = 'assets/images/parentesis/parentesis_1.png';
  final parentesis_2_png = 'assets/images/parentesis/parentesis_2.png';
  final parentesis_3_png = 'assets/images/parentesis/parentesis_3.png';
  final parentesis_4_png = 'assets/images/parentesis/parentesis_4.png';
  final parentesis_5_png = 'assets/images/parentesis/parentesis_5.png';
  final parentesis_6_png = 'assets/images/parentesis/parentesis_6.png';
  final parentesis_7_png = 'assets/images/parentesis/parentesis_7.png';
}

class _assets_images_regras_sinal_dart {
  final Brightness _brightness;

  _assets_images_regras_sinal_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final regras_sinais_1_png = 'assets/images/regras_sinal/regras_sinais_1.png';
  final regras_sinais_2_png = 'assets/images/regras_sinal/regras_sinais_2.png';
  final regras_sinais_3_png = 'assets/images/regras_sinal/regras_sinais_3.png';
  final regras_sinais_5_png = 'assets/images/regras_sinal/regras_sinais_5.png';
}

class _assets_images_soma_sub_dart {
  final Brightness _brightness;

  _assets_images_soma_sub_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final soma_sub_1_png = 'assets/images/soma_sub/soma_sub_1.png';
}

class _assets_svg_dart {
  final Brightness _brightness;

  _assets_svg_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final addition_subtraction_svg = 'assets/svg/addition_subtraction.svg';
  final compound_interest_svg = 'assets/svg/compound_interest.svg';
  final exponent_svg = 'assets/svg/exponent.svg';
  final factorial_svg = 'assets/svg/factorial.svg';
  final gcd_svg = 'assets/svg/gcd.svg';
  final lcm_svg = 'assets/svg/lcm.svg';
  final linear_equation_svg = 'assets/svg/linear_equation.svg';
  final multiplication_division_svg = 'assets/svg/multiplication_division.svg';
  final multiplication_table_svg = 'assets/svg/multiplication_table.svg';
  final parentheses_svg = 'assets/svg/parentheses.svg';
  final percentage_svg = 'assets/svg/percentage.svg';
  final quadratic_equation_svg = 'assets/svg/quadratic_equation.svg';
  final rule_of_three_svg = 'assets/svg/rule_of_three.svg';
  final sign_rules_svg = 'assets/svg/sign_rules.svg';
  final simple_interest_svg = 'assets/svg/simple_interest.svg';
}
